themes/DefaultTheme/src/routes/web.php
<?php

use Themes\DefaultTheme\src\Controllers\ReturnedController;
use Illuminate\Support\Facades\Route;
use Themes\DefaultTheme\src\Controllers\MainController;
use Themes\DefaultTheme\src\Controllers\PostController;
use Themes\DefaultTheme\src\Controllers\ProductController;
use Themes\DefaultTheme\src\Controllers\ReviewController;
use Themes\DefaultTheme\src\Controllers\CartController;
use Themes\DefaultTheme\src\Controllers\StockNotifyController;
use Themes\DefaultTheme\src\Controllers\PageController;
use Themes\DefaultTheme\src\Controllers\BrandController;
use Themes\DefaultTheme\src\Controllers\OrderController;
use Themes\DefaultTheme\src\Controllers\UserController;
use Themes\DefaultTheme\src\Controllers\SitemapController;
use Themes\DefaultTheme\src\Controllers\ContactController;
use Themes\DefaultTheme\src\Controllers\FavoriteController;
use Themes\DefaultTheme\src\Controllers\TicketController;
use Themes\DefaultTheme\src\Controllers\VerifyController;
use Themes\DefaultTheme\src\Controllers\DiscountController;
use Themes\DefaultTheme\src\Controllers\WalletController;

// ------------------ Front Part Routes

Route::group(['as' => 'front.'], function () {
    // ------------------ MainController
    Route::get('/', [MainController::class, 'index'])->name('index');
    Route::get('/get-new-captcha', [MainController::class, 'captcha']);

    // ------------------ posts
    Route::resource('posts', PostController::class)->only(['index', 'show']);
    Route::get('posts/category/{category}', [PostController::class, 'category'])->name('posts.category');

    // ------------------ products
    Route::resource('products', ProductController::class)->only(['show', 'index']);
    Route::get('products/category/{category}', [ProductController::class, 'category'])->name('products.category');
    Route::get('products/category-products/{category}', [ProductController::class, 'categoryProducts'])->name('products.category-products');
    Route::get('products/category-specials/{category}', [ProductController::class, 'categorySpecials'])->name('products.category-specials');
    Route::get('search', [ProductController::class, 'search'])->name('products.search');
    Route::post('search', [ProductController::class, 'ajax_search'])->name('products.ajax_search');
    Route::get('product/specials', [ProductController::class, 'specials'])->name('products.specials');
    Route::get('product/discount', [ProductController::class, 'discount'])->name('products.discount');
    Route::get('product/{product}/prices', [ProductController::class, 'prices'])->name('products.prices');
    Route::get('product/compare/{product1}/{product2?}/{product3?}', [ProductController::class, 'compare'])->name('products.compare');
    Route::post('product/compare', [ProductController::class, 'similarCompare'])->name('products.similar-compare');
    Route::get('products/{price}/priceChart', [ProductController::class, 'priceChart'])->name('products.priceChart');


    // ------------------ cart
    Route::get('cart', [CartController::class, 'show'])->name('cart');
    Route::post('cart/{product}', [CartController::class, 'store'])->name('cart.store');
    Route::put('cart', [CartController::class, 'update']);
    Route::delete('cart/{id}', [CartController::class, 'destroy'])->name('cart.destroy');

    Route::post('stock-notify', [StockNotifyController::class, 'store']);


    // ------------------ pages
    Route::get('pages/{page}', [PageController::class, 'show'])->name('pages.show');

    // ------------------ brands
    Route::get('brands/{brand}', [BrandController::class, 'show'])->name('brands.show');

    // ------------------ sitemap
    Route::get('sitemap', [SitemapController::class, 'index']);
    Route::get('sitemap-posts', [SitemapController::class, 'posts']);
    Route::get('sitemap-pages', [SitemapController::class, 'pages']);
    Route::get('sitemap-products', [SitemapController::class, 'products']);

    // ------------------ contacts
    Route::resource('contact', ContactController::class)->only(['index', 'store']);

    // ------------------ orders
    Route::any('orders/payment/callback/{gateway}', [OrderController::class, 'verify'])->name('orders.verify');

    // ------------------ wallet
    Route::any('wallet/payment/callback/{gateway}', [WalletController::class, 'verify'])->name('wallet.verify');
    
    // ------------------ returned
    Route::get('returned/{id}/create',[ReturnedController::class,'create'])->name('returned.create');
    Route::post('returned/{order}/store',[ReturnedController::class,'store'])->name('returned.store');
    Route::post('returned/traking/{return}',[ReturnedController::class,'traking'])->name('returned.traking');
    
    Route::get('returned/index',[ReturnedController::class,'index'])->name('returned/index');
    Route::get('returned/{returned}',[ReturnedController::class,'index_product'])->name('returned.index.product');
    
    // ------------------ authentication required
    Route::group(['middleware' => ['auth', 'verified', 'CheckPasswordChange']], function () {

        // ------------------ MainController
        Route::get('checkout', [MainController::class, 'checkout'])->name('checkout');
        Route::get('checkout-prices', [MainController::class, 'getPrices'])->name('checkout.prices');

        // ------------------ discount
        Route::post('discount', [DiscountController::class, 'store'])->name('discount.store');
        Route::delete('discount', [DiscountController::class, 'destroy'])->name('discount.destroy');

        // ------------------ orders
        Route::resource('orders', OrderController::class);
        Route::get('orders/pay/{order}', [OrderController::class, 'pay'])->name('orders.pay');

        // ------------------ wallet
        Route::resource('wallet', WalletController::class)->only(['index', 'show', 'create', 'store']);

        // ------------------ user
        Route::get('user/profile', [UserController::class, 'profile'])->name('user.profile');
        Route::get('user/comments', [UserController::class, 'comments'])->name('user.comments');
        Route::get('user/edit-profile', [UserController::class, 'editProfile'])->name('user.profile.edit');
        Route::put('user/profile', [UserController::class, 'update_profile'])->name('user.profile.update');
        Route::get('user/change-password', [UserController::class, 'changePassword'])->name('user.password');
        Route::put('user/change-password', [UserController::class, 'updatePassword'])->name('user.password.update');

        Route::group(['middleware' => ['EnsureForceChange']], function () {
            Route::get('user/force-change-password', [UserController::class, 'forceChangePassword'])->name('user.force-change-password');
            Route::post('user/force-change-password', [UserController::class, 'forceUpdatePassword'])->name('user.force-update-password');
        });

        // ------------------ products
        Route::get('products/{price}/download', [ProductController::class, 'download'])->name('products.download');
        Route::post('products/{product}/comments', [ProductController::class, 'comments'])->name('product.comments');

        // ------------------ reviews
        Route::resource('reviews', ReviewController::class)->only(['store', 'index']);
        Route::get('reviews/{product}', [ReviewController::class, 'show'])->name('reviews.show');
        Route::post('reviews/{review}/like', [ReviewController::class, 'like'])->name('reviews.like');
        Route::post('reviews/{review}/dislike', [ReviewController::class, 'dislike'])->name('reviews.dislike');

        // ------------------ posts
        Route::post('posts/{post}/comments', [PostController::class, 'comments'])->name('post.comments');

        // ------------------ favorites
        Route::resource('favorites', FavoriteController::class)->only(['index', 'store', 'destroy']);

        // ------------------ tickets
        Route::resource('tickets', TicketController::class)->except(['destroy']);
    });

    // ------------------ verify user routes
    Route::group(['middleware' => ['auth', 'notVerified', 'CheckPasswordChange']], function () {
        Route::get('verify', [VerifyController::class, 'showVerify'])->name('verify.showVerify');
        Route::post('verify', [VerifyController::class, 'verifyCode'])->name('verify.verifyCode')->middleware('throttle:15,1');
        Route::get('change-username', [VerifyController::class, 'showChangeUsername'])->name('verify.showChangeUsername');
        Route::post('change-username', [VerifyController::class, 'changeUsername'])->name('verify.changeUsername');
    });
});

// get auth user in 404 page
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

themes/DefaultTheme/src/resources/views/posts/partials/sidebar.blade.php
@if($latest_posts->count())
    <div class="col-lg-3 col-md-4 col-sm-12 col-12 mb-3 sidebar sticky-sidebar">
        <div class="widget-posts dt-sn dt-sl mb-3">
            <div class="title-sidebar dt-sl mb-3">
                <h3>{{ trans('front::messages.posts.the-latest-posts') }}</h3>
            </div>
            <div class="content-sidebar dt-sl">
                @foreach($latest_posts as $item)
                    <div class="item">
                        <div class="item-inner">
                            <div class="item-thumb">
                                <a href="{{ route('front.posts.show', ['post' => $item]) }}" class="img-holder" style="background-image: url('{{ $item->image ?: theme_asset('images/blog-empty-image.jpg') }}')"></a>
                            </div>
                            <p class="title">
                                <a href="{{ route('front.posts.show', ['post' => $item]) }}">{{ $item->title }}</a>
                            </p>
                            <div class="item-meta">
                                <span class="time">{{ jdate($item->created_at)->format('%d %B %Y') }}</span>
                            </div>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endif

themes/DefaultTheme/src/resources/views/reviews/index.blade.php
@extends('front::user.layouts.master')

@section('user-content')
    <!-- Start Content -->
    <div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
        <div class="row">
            <div class="col-12">
                <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                    <h2>نظرات شما</h2>
                </div>
                <div class="dt-sl reviews-container">
                    <div class="row">
                        @if($reviews->count())
                            @foreach($reviews as $review)
                                <div class="col-lg-6 col-md-12">
                                    <div class="card-horizontal-product">
                                        <div class="card-horizontal-product-thumb">
                                            <a title="{{ $review->product->title }}" href="{{ route('front.products.show', ['product' => $review->product]) }}">
                                                <img src="{{ $review->product->imageUrl() }}" alt="{{ $review->product->title }}">
                                            </a>
                                            <small class="font-weight-bold">امتیاز من به محصول</small>
                                            <div class="rating-stars">
                                                <i class="mdi mdi-star active"></i>
                                                <i class="mdi mdi-star {{ $review->rating > 1 ? 'active' : '' }}"></i>
                                                <i class="mdi mdi-star {{ $review->rating > 2 ? 'active' : '' }}"></i>
                                                <i class="mdi mdi-star {{ $review->rating > 3 ? 'active' : '' }}"></i>
                                                <i class="mdi mdi-star {{ $review->rating > 4 ? 'active' : '' }}"></i>
                                            </div>
                                        </div>
                                        <div class="card-horizontal-product-content">
                                            @switch($review->status)
                                                @case('accepted')
                                                    <div class="label-status-comment">تایید شده</div>
                                                    @break
                                                @case('pending')
                                                    <div class="label-status-comment">منتظر تایید</div>
                                                    @break
                                                @case('rejected')
                                                    <div class="label-status-comment">رد شده</div>
                                                    @break

                                            @endswitch

                                            <div class="card-horizontal-comment-title">
                                                <a href="{{ route('front.products.show', ['product' => $review->product]) }}">
                                                    <h3>{{ $review->title }}</h3>
                                                </a>
                                            </div>
                                            <div class="card-horizontal-comment">
                                                <p>{!! nl2br(htmlentities($review->body)) !!}</p>
                                            </div>
                                            <div class="card-horizontal-product-buttons">
                                                <div class="float-right">
                                                    <span class="count-like">
                                                        <i class="mdi mdi-thumb-up-outline"></i>{{ $review->likes_count }}
                                                    </span>
                                                    <span class="count-like">
                                                        <i class="mdi mdi-thumb-down-outline"></i>{{ $review->dislikes_count }}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach



                        @else
                            <div class="col-12">
                                <div class="page dt-sl dt-sn pt-3">
                                    <p>چیزی برای نمایش وجود ندارد</p>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-3">
            {{ $reviews->links('front::components.paginate') }}
        </div>

    </div>
    <!-- End Content -->
@endsection

themes/DefaultTheme/src/resources/views/user/wallet/create.blade.php
@extends('front::user.layouts.master')

@section('user-content')
    <div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
        <div class="px-3 px-res-0">
            @if ($errors->any())
                <div class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach
                </div>
            @endif

            <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                <h2>{{ trans('front::messages.wallet.increase-wallet-inventory') }}</h2>
            </div>
            <div class="form-ui additional-info dt-sl dt-sn pt-4">
                <form id="wallet-create-form" action="{{ route('front.wallet.store') }}" class="setting_form" method="POST">
                    @csrf

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-row-title">
                                <h3>{{ trans('front::messages.wallet.amount') }} ({{ trans('front::messages.currency.prefix') }}{{ trans('front::messages.currency.suffix') }})</h3>
                            </div>
                            <div class="form-row form-group">
                                <input type="number" class="input-ui pr-2 amount-input" name="amount">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-row-title">
                                <h3>{{ trans('front::messages.wallet.select-payment-gateway') }}</h3>
                            </div>
                            <div class="form-row form-group">
                                <select class="form-control py-0" name="gateway" required>
                                    <option value="">{{ trans('front::messages.wallet.select') }}</option>
                                    @foreach ($gateways as $gateway)
                                        <option value="{{ $gateway->key }}">{{ $gateway->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <div class="form-row mt-3 justify-content-center">
                        <button id="submit-btn" type="submit" class="btn-primary-cm btn-with-icon ml-2">
                            <i class="mdi mdi-arrow-left"></i>
                            {{ trans('front::messages.wallet.increase-inventory') }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ theme_asset('js/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ theme_asset('js/plugins/jquery-validation/localization/messages_fa.min.js') }}?v=2"></script>

    <script src="{{ theme_asset('js/pages/wallet/create.js') }}"></script>
@endpush

themes/DefaultTheme/src/resources/views/user/wallet/index.blade.php
@extends('front::user.layouts.master')

@section('user-content')
    <!-- Start Content -->
    <div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">

        @if($histories->count())

            <div class="row">
                @if(session('message') == 'ok')

                    <div class="col-lg-12 text-center">
                        <div class="alert alert-success mt-4" role="alert">
                            <strong>{{ trans('front::messages.wallet.inventory-increase-successful') }}</strong>.
                        </div>
                    </div>

                @elseif(session('transaction-error'))
                    <div class="col-lg-12 text-center">
                        <div class="alert alert-danger mt-4" role="alert">
                            <strong>{{ session('transaction-error') }}</strong>.
                        </div>
                    </div>
                @endif

                <div class="col-12">
                    <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                        <h2>{{ trans('front::messages.wallet.wallet-history') }}</h2>
                        <a href="{{ route('front.wallet.create') }}" class="m-0 d-block">{{ trans('front::messages.wallet.increase-wallet-inventory') }}</a>
                    </div>
                    <div class="dt-sl">
                        <div class="table-responsive">
                            <table class="table table-order">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{{ trans('front::messages.wallet.amount') }} ({{ trans('front::messages.currency.prefix') }}{{ trans('front::messages.currency.suffix') }})</th>
                                    <th>{{ trans('front::messages.wallet.type-of-transaction') }}</th>
                                    <th>{{ trans('front::messages.wallet.history') }}</th>
                                    <th class="text-center">{{ trans('front::messages.wallet.state') }}</th>
                                    <th>{{ trans('front::messages.wallet.details') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach ($histories as $history)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>

                                            @php
                                                $is_deposit = $history->type == 'deposit';
                                            @endphp

                                            <td class="{{ $is_deposit ? 'text-success' : 'text-danger' }}">{{ number_format($history->amount) }}</td>
                                            <td>
                                                @if ($is_deposit)
                                                {{ trans('front::messages.wallet.increase-credit') }}
                                                    <div class="badge badge-success ml-1">
                                                        <i class="mdi mdi-arrow-up"></i>
                                                    </div>
                                                @else
                                                {{ trans('front::messages.wallet.decrease-credit') }}
                                                    <div class="badge badge-danger ml-1">
                                                        <i class="mdi mdi-arrow-down"></i>
                                                    </div>
                                                @endif
                                            </td>
                                            <td class="ltr">{{ jdate($history->created_at) }}</td>

                                            <td class="text-center">
                                                @if($history->status == 'success')
                                                    <div class="badge badge-pill badge-success badge-md">{{ trans('front::messages.wallet.successful') }}</div>
                                                @else
                                                    <div class="badge badge-pill badge-danger badge-md">{{ trans('front::messages.wallet.unsuccessful') }}</div>
                                                @endif
                                            </td>

                                            <td class="details-link">
                                                <a class="show-history" data-action="{{ route('front.wallet.show', ['wallet' => $history]) }}" href="#" onclick="return false;">
                                                    <i class="mdi mdi-chevron-left"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        @else
            <div class="row">
                <div class="col-12">
                    <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                        <h2>{{ trans('front::messages.wallet.wallet-history') }}</h2>
                        <a href="{{ route('front.wallet.create') }}" class="m-0 d-block">{{ trans('front::messages.wallet.increase-wallet-inventory') }}</a>
                    </div>
                </div>
                <div class="col-12">
                    <div class="page dt-sl dt-sn pt-3">
                        <p>{{ trans('front::messages.wallet.there-is-nothing-to-show') }}</p>
                    </div>
                </div>
            </div>
        @endif

        <div class="mt-3">
            {{ $histories->links('front::components.paginate') }}
        </div>

    </div>
    <!-- End Content -->
@endsection

@push('scripts')
    <!-- show Modal -->
    <div class="modal fade" id="history-show-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel21">{{ trans('front::messages.wallet.transaction-details') }}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="history-detail" class="modal-body">


                </div>
            </div>
        </div>
    </div>

    <script src="{{ theme_asset('js/pages/wallet/index.js') }}"></script>
@endpush

themes/DefaultTheme/src/resources/views/user/wallet/show.blade.php
<div class="table-responsive">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row" style="min-width: 200px;">{{ trans('front::messages.wallet.id') }}</th>
                <td>{{ $history->id }}</td>
            </tr>

            <tr>
                <th scope="row">{{ trans('front::messages.wallet.amount') }}</th>
                <td>{{ trans('front::messages.currency.prefix') }}{{ number_format($history->amount) }}{{ trans('front::messages.currency.suffix') }}</td>
            </tr>
            <tr>
                <th scope="row">{{ trans('front::messages.wallet.type-of-transaction') }}</th>
                <td>
                    @if ($history->type == 'deposit')
                    {{ trans('front::messages.wallet.increase-credit') }}
                        <div class="badge badge-success ml-1">
                            <i class="mdi mdi-arrow-up"></i>
                        </div>
                    @else
                    {{ trans('front::messages.wallet.decrease-credit') }}
                        <div class="badge badge-danger ml-1">
                            <i class="mdi mdi-arrow-down"></i>
                        </div>
                    @endif
                </td>
            </tr>

            <tr>
                <th scope="row">{{ trans('front::messages.wallet.transaction-date') }}</th>
                <td class="ltr">{{ jdate($history->created_at) }}</td>
            </tr>
            <tr>
                <th scope="row">{{ trans('front::messages.wallet.state') }}</th>
                <td>
                    @if($history->status == 'success')
                        <div class="badge badge-pill badge-success badge-md">{{ trans('front::messages.wallet.successful') }}</div>
                    @else
                        <div class="badge badge-pill badge-danger badge-md">{{ trans('front::messages.wallet.unsuccessful') }}</div>
                    @endif
                </td>
            </tr>

            <tr>
                <th scope="row">{{ trans('front::messages.wallet.description') }}</th>
                <td>{!! $history->description !!}</td>
            </tr>

            @if ($history->order)
                <tr>
                    <th scope="row">{{ trans('front::messages.wallet.order-number') }}</th>
                    <td><a target="_blank" href="{{ route('front.orders.show', ['order' => $history->order]) }}">{{ $history->order->id }}</a></td>
                </tr>
            @endif

            @if ($history->transaction)
                <tr>
                    <th scope="row">{{ trans('front::messages.wallet.transaction-number') }}</th>
                    <td>{{ $history->transaction->transId }}</td>
                </tr>
                <tr>
                    <th scope="row">{{ trans('front::messages.wallet.issue-tracking') }}</th>
                    <td>{{ $history->transaction->traceNumber }}</td>
                </tr>
            @endif
        </tbody>
    </table>
</div>

themes/DefaultTheme/src/resources/views/widgets/coworker-sliders.blade.php
@php
    $variables          = get_widget($widget);
    $coworker_sliders   = $variables['coworker_sliders'];
@endphp


<!-- Start Partners -->
@if ($coworker_sliders->count())
<section class="slider-section dt-sl mb-3">
    <div class="row">
        <div class="col-12">
            <div class="brand-slider carousel-sm owl-carousel owl-theme">
                @foreach ($coworker_sliders as $slider)
                    <div class="item">
                        <img data-src="{{ $slider->image }}" class="img-fluid" alt="{{ $slider->title }}">
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</section>
@endif
<!-- End Partners -->

themes/DefaultTheme/src/resources/views/widgets/posts.blade.php
@php
    $variables      = get_widget($widget);
    $posts          = $variables['posts'];
@endphp

<!-- Start posts -->
@if ($posts->count())
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <section class="slider-section dt-sl mb-3">
                <div class="row mb-3">
                    <div class="col-12">
                        <div class="section-title text-sm-title title-wide no-after-title-wide">
                            <h2>{{ $widget->option('title') }}</h2>
                            @if ($widget->option('link'))
                                <a href="{{ $widget->option('link') }}">{{ $widget->option('link_title', trans('front::messages.user.see-all') ) }}</a>
                            @endif
                        </div>
                    </div>

                    <div class="col-12 px-res-0">
                        <div class="product-carousel carousel-md owl-carousel owl-theme posts-widget-owl">
                            @foreach ($posts as $post)
                                <div class="item">
                                    <div class="post-card mb-0">
                                        <div class="post-thumbnail">
                                            <a href="{{ route('front.posts.show', ['post' => $post]) }}">
                                                <img src="{{ theme_asset('images/blog-empty-image.jpg') }}" data-src="{{ $post->image ? asset($post->image) : theme_asset('images/blog-empty-image.jpg') }}" alt="{{ $post->title }}">
                                            </a>
                                            <span class="post-tag">{{ $post->category ? $post->category->title : trans('front::messages.user.uncategorized')  }}</span>

                                        </div>
                                        <div class="post-title">
                                            <a href="{{ route('front.posts.show', ['post' => $post]) }}">{{ $post->title }}</a>
                                            <span class="post-date">{{ jdate($post->created_at)->format('%d %B %Y') }}</span>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endif
<!-- End posts -->