routes/web.php
<?php

use App\Http\Controllers\Back\ApikeyController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Back\ProvinceController;
use App\Http\Controllers\Back\MainController;
use App\Http\Controllers\Back\UserController;
use App\Http\Controllers\Back\ProductController;
use App\Http\Controllers\Back\BrandController;
use App\Http\Controllers\Back\FilterController;
use App\Http\Controllers\Back\AttributeGroupController;
use App\Http\Controllers\Back\AttributeController;
use App\Http\Controllers\Back\BackupController;
use App\Http\Controllers\Back\SpecTypeController;
use App\Http\Controllers\Back\PostController;
use App\Http\Controllers\Back\CategoryController;
use App\Http\Controllers\Back\PageController;
use App\Http\Controllers\Back\MenuController;
use App\Http\Controllers\Back\OrderController;
use App\Http\Controllers\Back\TransactionController;
use App\Http\Controllers\Back\SliderController;
use App\Http\Controllers\Back\BannerController;
use App\Http\Controllers\Back\CarrierController;
use App\Http\Controllers\Back\CityController;
use App\Http\Controllers\Back\LinkController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\StockNotifyController;
use App\Http\Controllers\Back\CommentController;
use App\Http\Controllers\Back\CurrencyController;
use App\Http\Controllers\Back\DeveloperController;
use App\Http\Controllers\Back\DiscountController;
use App\Http\Controllers\Back\InstallController;
use App\Http\Controllers\Back\RoleController;
use App\Http\Controllers\Back\PermissionController;
use App\Http\Controllers\Back\ReviewController;
use App\Http\Controllers\Back\SettingController;
use App\Http\Controllers\Back\SmsController;
use App\Http\Controllers\Back\StatisticsController;
use App\Http\Controllers\Back\TariffController;
use App\Http\Controllers\Back\ThemeController;
use App\Http\Controllers\Back\TicketController;
use App\Http\Controllers\Back\WalletController;
use App\Http\Controllers\Back\WalletHistoryController;
use App\Http\Controllers\Back\WidgetController;
use App\Http\Controllers\PushSubscriptionController;
use App\Http\Controllers\ReturnedController;
use App\Http\Controllers\ReturnedItemController;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::get('province/get-cities', [ProvinceController::class, 'getCities'])->name('provinces.get-cities');

Route::group(['as' => 'admin.', 'prefix' => 'admin/' . admin_route_prefix(), 'middleware' => ['guest']], function () {
    Route::get('login', [MainController::class, 'login'])->middleware(['CheckUserExists'])->name('login');
    Route::get('register', [InstallController::class, 'showRegisterForm'])->name('register')->middleware(['CheckUserNotExists']);
    Route::post('register', [InstallController::class, 'register'])->middleware(['CheckUserNotExists']);
});

// ------------------ Admin Part Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin/' . admin_route_prefix(), 'middleware' => ['auth', 'Admin', 'verified', 'CheckPasswordChange', 'password.confirm']], function () {

    // ------------------ MainController
    Route::get('/', [MainController::class, 'index'])->name('dashboard');
    Route::get('get-tags', [MainController::class, 'get_tags'])->name('get-tags');
    Route::get('get-labels', [MainController::class, 'getLabels'])->name('get-labels');

    Route::get('notifications', [MainController::class, 'notifications'])->name('notifications');

    Route::get('file-manager', [MainController::class, 'fileManager'])->name('file-manager');
    Route::get('file-manager-iframe', [MainController::class, 'fileManagerIframe'])->name('file-manager-iframe');

    // ------------------ backups
    Route::get('backups', [BackupController::class, 'index'])->name('backups.index');
    Route::post('backups/create', [BackupController::class, 'create'])->name('backups.create');
    Route::get('backups/{backup}/download', [BackupController::class, 'download'])->name('backups.download');
    Route::delete('backups/{backup}', [BackupController::class, 'destroy'])->name('backups.destroy');

    // ------------------ users
    Route::resource('users', UserController::class);
    Route::post('users/api/index', [UserController::class, 'apiIndex'])->name('users.apiIndex');
    Route::delete('users/api/multipleDestroy', [UserController::class, 'multipleDestroy'])->name('users.multipleDestroy');
    Route::get('users/export/create', [UserController::class, 'export'])->name('users.export');
    Route::get('users/{user}/views', [UserController::class, 'views'])->name('users.views');
    Route::get('user/profile', [UserController::class, 'showProfile'])->name('user.profile.show');
    Route::put('user/profile', [UserController::class, 'updateProfile'])->name('user.profile.update');

    // ------------------ wallets
    Route::resource('wallets', WalletController::class)->only(['show', 'index']);
    Route::get('wallets/histories/{history}', [WalletController::class, 'history'])->name('wallets.history');
    Route::get('wallets/{wallet}/create', [WalletController::class, 'create'])->name('wallets.create');
    Route::post('wallets/{wallet}', [WalletController::class, 'store'])->name('wallets.store');

    // ------------------ products
    Route::resource('products', ProductController::class)->except('show');
    Route::post('products/api/index', [ProductController::class, 'apiIndex'])->name('products.apiIndex');
    Route::delete('products/api/multipleDestroy', [ProductController::class, 'multipleDestroy'])->name('products.multipleDestroy');
    Route::post('products/image-store', [ProductController::class, 'image_store']);
    Route::post('products/image-delete', [ProductController::class, 'image_delete']);
    Route::get('product/categories', [ProductController::class, 'categories'])->name('products.categories.index');
    Route::post('product/slug', [ProductController::class, 'generate_slug']);

    Route::get('products/export/create', [ProductController::class, 'export'])->name('products.export');

    Route::get('product/prices', [ProductController::class, 'indexPrices'])->name('product.prices.index');
    Route::put('product/prices', [ProductController::class, 'updatePrices'])->name('product.prices.update');

    // ------------------ discounts
    Route::resource('discounts', DiscountController::class)->except(['show']);

    // ------------------ provinces
    Route::resource('provinces', ProvinceController::class);
    Route::post('provinces/api/index', [ProvinceController::class, 'apiIndex'])->name('provinces.apiIndex');
    Route::delete('provinces/api/multipleDestroy', [ProvinceController::class, 'multipleDestroy'])->name('provinces.multipleDestroy');
    Route::post('provinces/api/sort', [ProvinceController::class, 'sort'])->name('provinces.sort');

    // ------------------ cities
    Route::resource('cities', CityController::class)->except(['index']);
    Route::post('cities/api/{province}/index', [CityController::class, 'apiIndex'])->name('cities.apiIndex');
    Route::delete('cities/api/multipleDestroy', [CityController::class, 'multipleDestroy'])->name('cities.multipleDestroy');
    Route::post('cities/api/sort', [CityController::class, 'sort'])->name('cities.sort');

    // ------------------ brands
    Route::resource('brands', BrandController::class)->except('show');
    Route::get('brands/ajax/get', [BrandController::class, 'ajax_get']);
    
    // ------------------ returned
    Route::get('returned/show',[ReturnedController::class,'show'])->name('returned.show');
    Route::get('returned/prduct-index/{returned}',[ReturnedController::class,'index'])->name('return.product.index');
    Route::post('returnde/api/index', [ReturnedController::class, 'apiIndex'])->name('returned.apiIndex');
    Route::post('returned/update/{return}',[ReturnedItemController::class,'update'])->name('return.update');
  
    // ------------------ filters
    Route::resource('filters', FilterController::class)->except('show');

    // ------------------ attributeGroups
    Route::resource('attributeGroups', AttributeGroupController::class);
    Route::get('attributeGroups/{attributeGroup}/attributes', [AttributeGroupController::class, 'attributesIndex'])->name('attributes.index');
    Route::post('attributeGroup/sort', [AttributeGroupController::class, 'sort']);

    // ------------------ attributes
    Route::resource('attributes', AttributeController::class)->except(['index', 'show']);

    // ------------------ spec types
    Route::get('spectypes/spec-type-data', [SpecTypeController::class, 'getData'])->name('spectypes.getdata');
    Route::get('spectypes/ajax/get', [SpecTypeController::class, 'ajax_get']);
    Route::resource('spectypes', SpecTypeController::class)->except(['show', 'create']);


    // ------------------ posts
    Route::resource('posts', PostController::class)->except(['show']);
    Route::get('post/categories', [PostController::class, 'categories'])->name('posts.categories.index');
    Route::post('post/slug', [PostController::class, 'generate_slug']);


    // ------------------ categories
    Route::resource('categories', CategoryController::class)->only(['update', 'destroy', 'store', 'edit']);
    Route::post('categories/sort', [CategoryController::class, 'sort']);
    Route::post('category/slug', [CategoryController::class, 'generate_slug']);


    // ------------------ pages
    Route::resource('pages', PageController::class)->except(['show']);

    // ------------------ apikeys
    Route::resource('apikeys', ApikeyController::class)->except(['show']);

app/Http/Controllers/Back/ApikeyController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Requests\Back\Apikey\StoreApikeyRequest;
use App\Http\Requests\Back\Apikey\UpdateApikeyRequest;
use App\Models\Apikey;
use Illuminate\Http\Request;

class ApikeyController extends Controller
{
    public function index()
    {
        $apikeys = Apikey::latest()->get();

        return view('back.apikeys.index', compact('apikeys'));
    }

    public function create()
    {
        return view('back.apikeys.create');
    }

    public function store(StoreApikeyRequest $request)
    {
        $data = $request->validated();

        Apikey::create($data);

        toastr()->success('کلید وب سرویس با موفقیت ایجاد شد.');

        return response('success');
    }

    public function edit(Apikey $apikey)
    {
        return view('back.apikeys.edit', compact('apikey'));
    }

    public function update(Apikey $apikey, UpdateApikeyRequest $request)
    {
        $data = $request->validated();

        $apikey->update($data);

        toastr()->success('کلید وب سرویس با موفقیت ویرایش شد.');

        return response('success');
    }

    public function destroy(Apikey $apikey)
    {
        $apikey->delete();

        return response('success');
    }
}

app/Http/Controllers/Back/AttributeController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Attribute;
use App\Models\AttributeGroup;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AttributeController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Attribute::class, 'attribute');
    }

    public function create()
    {
        $attributeGroups = AttributeGroup::all();

        return view('back.attributes.create', compact('attributeGroups'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'               => 'required',
            'attribute_group_id' => 'required|exists:attribute_groups,id'
        ]);

        Attribute::create([
            'name'                => $request->name,
            'value'               => $request->value,
            'attribute_group_id'  => $request->attribute_group_id,
        ]);

        toastr()->success('ویژگی با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(Attribute $attribute)
    {
        $attributeGroups = AttributeGroup::all();

        return view('back.attributes.edit', compact('attribute', 'attributeGroups'));
    }

    public function update(Attribute $attribute, Request $request)
    {
        $this->validate($request, [
            'name'               => 'required',
            'attribute_group_id' => 'required|exists:attribute_groups,id'
        ]);

        $attribute->update([
            'name'                => $request->name,
            'value'               => $request->value,
            'attribute_group_id'  => $request->attribute_group_id,
        ]);

        toastr()->success('ویژگی با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(Attribute $attribute)
    {
        $attribute->delete();

        return response('success');
    }
}

app/Http/Controllers/Back/AttributeGroupController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\AttributeGroup;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AttributeGroupController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(AttributeGroup::class, 'attributeGroup');
    }

    public function index()
    {
        $attributeGroups = AttributeGroup::detectLang()->orderBy('ordering')->get();

        return view('back.attributeGroups.index', compact('attributeGroups'));
    }

    public function attributesIndex(AttributeGroup $attributeGroup)
    {
        $attributes = $attributeGroup->get_attributes()->paginate(15);

        return view('back.attributes.index', compact('attributes'));
    }

    public function create()
    {
        return view('back.attributeGroups.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'type' => 'required|in:color,checkbox',
        ]);

        $ordering = AttributeGroup::max('ordering') + 1;

        AttributeGroup::create([
            'name'       => $request->name,
            'lang'       => app()->getLocale(),
            'type'       => $request->type,
            'ordering'   => $ordering
        ]);

        toastr()->success('گروه ویژگی با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(AttributeGroup $attributeGroup)
    {
        return view('back.attributeGroups.edit', compact('attributeGroup'));
    }

    public function update(AttributeGroup $attributeGroup, Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'type' => 'required|in:color,checkbox',
        ]);

        $attributeGroup->update([
            'name'       => $request->name,
            'type'       => $request->type,
        ]);

        toastr()->success('گروه ویژگی با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(AttributeGroup $attributeGroup)
    {
        $attributeGroup->delete();

        return response('success');
    }

    public function sort(Request $request)
    {
        $this->authorize('attributes.groups.update');

        $this->validate($request, [
            'attributeGroups' => 'required|array'
        ]);

        $i = 1;

        foreach ($request->attributeGroups as $attributeGroup) {
            AttributeGroup::findOrFail($attributeGroup)->update([
                'ordering' => $i++,
            ]);
        };

        return response('success');
    }
}

app/Http/Controllers/Back/BackupController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Jobs\CreateBackup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BackupController extends Controller
{
    public function index()
    {
        $this->authorize('backups.index');

        $backups = Storage::disk('backup')->allFiles(config('backup.backup.name'));

        foreach ($backups as $key => $backup) {
            $backups[$key] = [];
            $backups[$key]['date'] =  Storage::disk('backup')->lastModified($backup);
            $backups[$key]['name'] =  substr($backup, strrpos($backup, '/') + 1);
            $backups[$key]['size'] =  number_format(Storage::disk('backup')->size($backup) / 1048576, 2) . ' mb';
        }

        $backups = collect($backups);

        return view('back.backups.index', compact('backups'));
    }

    public function create()
    {
        $this->authorize('backups.create');

        CreateBackup::dispatchAfterResponse();

        return response('success');
    }

    public function download($backup)
    {
        $this->authorize('backups.download');

        $filename = config('backup.backup.name') . '/' . $backup;

        if (!Storage::disk('backup')->exists($filename)) {
            abort(404);
        }

        return Storage::disk('backup')->download($filename);
    }

    public function destroy($backup)
    {
        $this->authorize('backups.delete');

        $filename = config('backup.backup.name') . '/' . $backup;

        if (!Storage::disk('backup')->exists($filename)) {
            abort(404);
        }

        Storage::disk('backup')->delete($filename);
        return response('success');
    }
}

resources/views/back/partials/banners.blade.php
@if($banners->count())
    <section class="card banners-sortable">
        <div class="card-header">
            <h4 class="card-title">{{ $title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead>
                            <tr>
                                <th class="text-center">ردیف</th>
                                <th>تصویر</th>
                                <th>عنوان</th>
                                <th class="text-center">وضعیت</th>
                                <th class="text-center">عملیات</th>
                            </tr>
                        </thead>
                        <tbody id="banners-sortable-{{ $loop->index }}">
                            @foreach($banners as $banner)
                                <tr id="banner-{{ $banner->id }}">
                                    <td class="text-center draggable-handler">
                                        <div class="fonticon-wrap"><i class="feather icon-move"></i></div>
                                    </td>
                                    <td>
                                        <div class="slider-thumb">
                                            <img src="{{ asset($banner->image) }}" alt="banner image">
                                        </div>
                                    </td>
                                    <td>{{ $banner->title ?: '--' }}</td>
                                    <td class="text-center">
                                        @if($banner->published)
                                            <div class="badge badge-pill badge-success badge-md">منتشر شده</div>
                                        @else
                                            <div class="badge badge-pill badge-danger badge-md">پیش نویس</div>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @can('banners.update')
                                            <a href="{{ route('admin.banners.edit', ['banner' => $banner]) }}" class="btn btn-info mr-1 waves-effect waves-light">ویرایش</a>
                                        @endcan

                                        @can('banners.delete')
                                            <button type="button" data-banner="{{ $banner->id }}" class="btn btn-danger mr-1 waves-effect waves-light btn-delete"  data-toggle="modal" data-target="#delete-modal">حذف</button>
                                        @endcan

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

@else
    <section class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="card-text">
                    <p>چیزی برای نمایش وجود ندارد!</p>
                </div>
            </div>
        </div>
    </section>
@endif

resources/views/back/partials/child_category.blade.php
<li class="dd-item" data-id="{{ $child_category->id }}">
    @if($child_category->categories->isEmpty())
        <div class="dd-handle"><span class="category-title">{{  $child_category->title  }}</span>
            <a data-category="{{ $child_category->slug }}" class="float-right delete-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-trash text-danger px-1"></i>حذف</a>
            <a data-category="{{ $child_category->slug }}" class="float-right edit-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-pencil text-info px-1"></i>ویرایش</a>
        </div>
    @else
        <div class="dd-handle"><span class="category-title">{{ $child_category->title }}</span>
            <a data-category="{{ $child_category->slug }}" class="float-right delete-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-trash text-danger px-1"></i>حذف</a>
            <a data-category="{{ $child_category->slug }}" class="float-right edit-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-pencil text-info px-1"></i>ویرایش</a>
        </div>
        <ol class="dd-list">
            @foreach ($child_category->childrenCategories as $childCategory)
                @include('back.partials.child_category', ['child_category' => $childCategory])
            @endforeach
        </ol>
    @endif
</li>

resources/views/back/partials/global-css.blade.php
<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('back/app-assets/css-rtl/custom-rtl.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('back/assets/css/style-rtl.css') }}?v=11">
<!-- END: Custom CSS-->

<!-- font css file -->
@if (user_option('theme_font', 'Vazir') == 'Vazir')
    <link rel="stylesheet" type="text/css" href="{{ asset('back/assets/fonts/vazir/style.css') }}">
@else
    <link rel="stylesheet" type="text/css" href="{{ asset('back/assets/fonts/iransansdn/style.css') }}">
@endif

resources/views/back/partials/header.blade.php
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu floating-nav navbar-light navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#">
                                <i class="ficon feather icon-menu"></i>
                            </a>
                        </li>
                    </ul>

                </div>
                <ul class="nav navbar-nav float-right align-items-center">
                    @if (option('multi_language_enabled'))
                        <li class="dropdown dropdown-language nav-item">
                            <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="selected-language">{{ $current_local['name'] }}</span></a>
                            <div class="dropdown-menu" aria-labelledby="dropdown-flag">
                                @foreach (get_langs() as $key => $lang)
                                    <a class="dropdown-item" href="{{ get_current_url($key) }}"> {{ $lang['name'] }}</a>
                                @endforeach
                            </div>
                        </li>
                    @endif

                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand">
                        <i class="ficon feather icon-maximize"></i></a>
                    </li>

                    @include('back.partials.notifications')

                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none"><span class="user-name text-bold-600">{{ auth()->user()->name }}</span></div>
                            <span><img class="round" src="{{ auth()->user()->imageUrl }}" alt="avatar" height="40" width="40"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="{{ route('admin.user.profile.show') }}">
                            <i class="feather icon-user"></i> ویرایش پروفایل</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}">
                                <i  class="feather icon-power"></i> خروج
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/back/partials/meta.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="laravel shop description">
<meta name="keywords" content="keywords">
<meta name="author" content="laravel shop">
<meta name="robots" content="noindex, nofollow">
<meta name="csrf-token" data-refresh-url="{{ route('csrf') }}" content="{{ csrf_token() }}">
<link rel="apple-touch-icon" href="{{ asset('back/app-assets/images/ico/apple-icon-120.png') }}">
<link rel="shortcut icon" type="image/x-icon" href="{{ asset('back/app-assets/images/ico/favicon-32x32.png') }}">

<!-- GCM Manifest (optional if VAPID is used) -->
@if (config('webpush.gcm.sender_id'))
    <link rel="manifest" href="{{ asset('manifest.json') }}">
@endif

resources/views/back/partials/notifications.blade.php
<li class="dropdown dropdown-notification nav-item"><a class="nav-link nav-link-label" href="#"
        data-toggle="dropdown"><i class="ficon feather icon-bell"></i><span
            class="badge badge-pill badge-primary badge-up">{{ $notifications->count() ?: '' }}</span></a>
    <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
        <li class="dropdown-menu-header">
            <div class="dropdown-header m-0 p-2">
                <h4 class="white">{{ $notifications->count() }} اعلان جدید</h4>
            </div>
        </li>
        <li class="scrollable-container media-list">
            @foreach ($notifications as $notification)
                @if($notification->type == 'OrderPaid')

                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-plus-square font-medium-5 primary"></i></div>
                            <div class="media-body">
                                <h6 class="primary media-heading">سفارش جدید ثبت شد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ jdate($notification->created_at)->ago() }}</time></small>
                        </div>
                    </a>

                @elseif($notification->type == 'UserRegistered')
                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-user font-medium-5 success"></i></div>
                            <div class="media-body">
                                <h6 class="success media-heading">کاربر جدید ثبت نام کرد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ jdate($notification->created_at)->ago() }}</time></small>
                        </div>
                    </a>

                @elseif($notification->type == 'ContactCreated')
                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-message-square font-medium-5 info"></i></div>
                            <div class="media-body">
                                <h6 class="info media-heading">پیام جدید دریافت شد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ jdate($notification->created_at)->ago() }}</time></small>
                        </div>
                    </a>
                @endif
            @endforeach
        </li>
        <li class="dropdown-menu-footer">
            <a class="dropdown-item p-1 text-center" href="{{ route('admin.notifications') }}">نمایش همه اعلان ها</a>
        </li>
    </ul>
</li>